"""v4

Revision ID: 024e4a09123c
Revises: 3b4757fbc93a
Create Date: 2024-10-08 15:17:16.132745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024e4a09123c'
down_revision: Union[str, None] = '3b4757fbc93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('focus_group_title', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('focus_group_description', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('focus_group_objective', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('disscussion_topic', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('top_ideas', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('validation_survey_title', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('questions', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('file_upload', sa.Boolean(), nullable=True))
    op.add_column('agents', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('context', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('file_type', sa.String(length=10), nullable=True))
    op.add_column('agents', sa.Column('upload_url', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('is_custom_agent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_custom_agent')
    op.drop_column('agents', 'upload_url')
    op.drop_column('agents', 'file_type')
    op.drop_column('agents', 'context')
    op.drop_column('agents', 'file_name')
    op.drop_column('agents', 'file_upload')
    op.drop_column('agents', 'questions')
    op.drop_column('agents', 'validation_survey_title')
    op.drop_column('agents', 'top_ideas')
    op.drop_column('agents', 'disscussion_topic')
    op.drop_column('agents', 'focus_group_objective')
    op.drop_column('agents', 'focus_group_description')
    op.drop_column('agents', 'focus_group_title')
    # ### end Alembic commands ###
