"""v3

Revision ID: 3b4757fbc93a
Revises: da155ff33cad
Create Date: 2024-10-05 10:06:13.996337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b4757fbc93a'
down_revision: Union[str, None] = 'da155ff33cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('tools', sa.JSON(), nullable=True))
    op.drop_constraint('tools_ibfk_1', 'tools', type_='foreignkey')
    op.drop_column('tools', 'agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('agent_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('tools_ibfk_1', 'tools', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('agents', 'tools')
    # ### end Alembic commands ###
