"""v7

Revision ID: 464d4ea8b38f
Revises: 675f5994be20
Create Date: 2024-10-10 11:28:02.233888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '464d4ea8b38f'
down_revision: Union[str, None] = '675f5994be20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('file_url', sa.String(length=255), nullable=True))
    op.drop_column('agents', 'upload_url')
    op.drop_column('agents', 'file_name')
    op.drop_column('agents', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('file_type', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('agents', sa.Column('file_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('agents', sa.Column('upload_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('agents', 'file_url')
    # ### end Alembic commands ###
