"""v8_agent_fields_added

Revision ID: 5fc8282be18d
Revises: 464d4ea8b38f
Create Date: 2024-10-17 17:11:36.528739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc8282be18d'
down_revision: Union[str, None] = '464d4ea8b38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_chatbot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_chatbot')
    # ### end Alembic commands ###
