"""v6

Revision ID: 675f5994be20
Revises: acbbc1c9474f
Create Date: 2024-10-09 15:35:37.093708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '675f5994be20'
down_revision: Union[str, None] = 'acbbc1c9474f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('discussion_topic', sa.Text(), nullable=True))
    op.drop_column('agents', 'disscussion_topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('disscussion_topic', mysql.TEXT(), nullable=True))
    op.drop_column('agents', 'discussion_topic')
    # ### end Alembic commands ###
