"""v5

Revision ID: acbbc1c9474f
Revises: 024e4a09123c
Create Date: 2024-10-09 14:17:26.274098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'acbbc1c9474f'
down_revision: Union[str, None] = '024e4a09123c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('validation_survey_title', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('vector_id', sa.String(length=36), nullable=True))
    op.drop_column('agents', 'validaion_servey_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('validaion_servey_title', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('agents', 'vector_id')
    op.drop_column('agents', 'validation_survey_title')
    # ### end Alembic commands ###
