"""v2_add_fields

Revision ID: da155ff33cad
Revises: 1ed02b248b26
Create Date: 2024-10-04 16:42:28.183853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da155ff33cad'
down_revision: Union[str, None] = '1ed02b248b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('attachments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attachments')
    op.drop_column('tasks', 'comment')
    # ### end Alembic commands ###
